export const HOME_SCREEN = "Home"
export const WINGS_OF_FAITH_LIST = "Recueil d'ensemble"
export const SONG_DETAIL = "Song"
export const ABOUT_SCREEN = "About"
export const CHURCH_BOOK_SONGS = "Recueil d'ensemble"
export const CHORUS_BOOK_SONGS = "Recueil chorale"
export const PREDICATIONS_SCREEN = "Predications"
